import { Roboto, Montserrat } from "next/font/google";
import "./globals.css";
import { FoodProvider } from "./context/FoodContext";
import Footer from "@/ui/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Food Recipe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <FoodProvider>
          {children} <Footer />
        </FoodProvider>
      </body>
    </html>
  );
}
