import { Roboto, Montserrat } from "next/font/google";
import "./globals.css";
import { FoodProvider } from "./context/FoodContext";
import Footer from "@/ui/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Food Recipe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100..700;1,100..700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${montserrat.className}`}>
        <FoodProvider>
          {children} <Footer />
        </FoodProvider>
      </body>
    </html>
  );
}
